spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
  forward-headers-strategy: framework
